# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://jredeker.github.io/
baseurl: /blog
title: Jon Redeker
author: Jon Redeker
description: Personal blog and resume
avatar: profile.jpg
email: jon.redeker@gmail.com
github: jredeker/jredeker.github.io # username
twitter: jonhredeker
linkedin: jredeker
#stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
disqus: username
#google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]

prose:
  rooturl: '_posts'
  siteurl: 'http://jredeker.github.io/'
  relativeLinks: 'http://jredeker.github.io/links.jsonp'
  media: 'images'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "published"
          field:
            label: "Published"
            element: "checkbox"
            value: "true"
     - name: "title"
         field:
           label: "Title"
           element: "text"
           value: "An Awesome Headline!"
     - name: "modified"
         field:
           element: "text"
           label: "Has this page been modified?"
           placeholder: "YYYY-MM-DD"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Development"
              value: "dev"
            - name: "Comedy"
              value: "comdedy"
            - name: "Sports"
              value: "sports"
            - name: "Opinion"
              value: "opinion"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
